name: TEST-BO-CICD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run something
      run: echo "✅ It works"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CICD }}

    - name: Build and push image
      env:
        APP_NAME: test-bot
      run: make image push
